import {
  BrainCircuit,
  Bot,
  Code2,
  Database,
  FileSearch,
  GitMerge,
  HeartHandshake,
  Key,
  Layers,
  PenLine,
  Server,
  Sparkles,
  Target,
  Terminal,
  Users,
  Zap,
} from "lucide-react";
import {
  SiAntdesign,
  SiApachekafka,
  SiDocker,
  SiExpress,
  SiFirebase,
  SiGit,
  SiGooglecloud,
  SiGraphql,
  SiJavascript,
  SiJira,
  SiLinux,
  SiMui,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiReact,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";
import type { SkillCategory, SoftSkill } from "./types";

export const skillCategories: SkillCategory[] = [
  {
    title: "Frontend",
    icon: Code2,
    skills: [
      { name: "React.js", icon: SiReact, level: "Advanced", percent: 90 },
      { name: "Next.js", icon: SiNextdotjs, level: "Advanced", percent: 95 },
      {
        name: "JavaScript",
        icon: SiJavascript,
        level: "Advanced",
        percent: 95,
      },
      {
        name: "TypeScript",
        icon: SiTypescript,
        level: "Advanced",
        percent: 90,
      },
      {
        name: "Tailwind CSS",
        icon: SiTailwindcss,
        level: "Proficient",
        percent: 80,
      },
      {
        name: "Ant Design",
        icon: SiAntdesign,
        level: "Intermediate",
        percent: 80,
      },
      { name: "MUI", icon: SiMui, level: "Proficient", percent: 72 },
      { name: "Shadcn/ui", icon: Layers, level: "Proficient", percent: 70 },
    ],
  },
  {
    title: "Backend",
    icon: Server,
    skills: [
      { name: "Node.js", icon: SiNodedotjs, level: "Advanced", percent: 90 },
      { name: "Express.js", icon: SiExpress, level: "Advanced", percent: 92 },
      {
        name: "PostgreSQL",
        icon: SiPostgresql,
        level: "Proficient",
        percent: 90,
      },
      { name: "NestJS", icon: SiNestjs, level: "Proficient", percent: 75 },
      { name: "Prisma", icon: SiPrisma, level: "Proficient", percent: 73 },
      { name: "TypeORM", icon: Database, level: "Intermediate", percent: 73 },
      { name: "GraphQL", icon: SiGraphql, level: "Intermediate", percent: 62 },
      { name: "Python", icon: SiPython, level: "Intermediate", percent: 60 },
      {
        name: "Firebase",
        icon: SiFirebase,
        level: "Intermediate",
        percent: 60,
      },
      {
        name: "Kafka",
        icon: SiApachekafka,
        level: "Intermediate",
        percent: 58,
      },
      { name: "Keystone.js", icon: Key, level: "Intermediate", percent: 55 },
      { name: "Debezium", icon: Database, level: "Intermediate", percent: 45 },
    ],
  },
  {
    title: "Tools & DevOps",
    icon: Terminal,
    skills: [
      { name: "Git", icon: SiGit, level: "Advanced", percent: 85 },
      { name: "Jira", icon: SiJira, level: "Proficient", percent: 75 },
      { name: "Linux CLI", icon: SiLinux, level: "Proficient", percent: 73 },
      { name: "Draw.io", icon: PenLine, level: "Proficient", percent: 70 },
      { name: "Docker", icon: SiDocker, level: "Intermediate", percent: 60 },
      { name: "GCP", icon: SiGooglecloud, level: "Intermediate", percent: 55 },
      {
        name: "CI/CD Pipelines",
        icon: GitMerge,
        level: "Beginner",
        percent: 35,
      },
    ],
  },
  {
    title: "AI & Automation",
    icon: BrainCircuit,
    skills: [
      { name: "Flowise", icon: Bot, level: "Proficient", percent: 85 },
      { name: "Claude AI", icon: Sparkles, level: "Intermediate", percent: 80 },
      { name: "OpenClaw", icon: Sparkles, level: "Beginner", percent: 60 },
      {
        name: "LlamaExtract",
        icon: FileSearch,
        level: "Beginner",
        percent: 35,
      },
    ],
  },
];

export const softSkills: SoftSkill[] = [
  { name: "Self-Leadership", icon: Target },
  { name: "Results-Oriented", icon: Zap },
  { name: "Effective Collaborator", icon: HeartHandshake },
  { name: "Adaptable & Fast Learner", icon: Users },
];
